apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
  - protocol: TCP
    port: 80        # Port exposed on the Service
    targetPort: 3000 # Port on which the app is running in the container
    nodePort: 30007  # Port on the node